### ISSUE TITLE
Assignment 2 - Wireframe

### ISSUE THREAD

**Issue by ymart1n** [ymart1n/EECE571G_Project_ArcadeSwap#2]
https://www.figma.com/file/EySR5SRjIzq04MIdEPaN6H/571G-Project-UI?node-id=0%3A1&t=BcKdsB2r8AoENb2N-1

**Comment by ziwei11** [comment]
https://www.figma.com/file/Q7m8uWK0xxe19Vw2SrjDvK/Assignment2-Wireframe?t=HbGdfyEeqxhpPDMc-6
